version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 100
      runas: root
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 100
      runas: root
